# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f99298b5e79d596d4871ed9288023c513599e454d615005bef3430f496db6f9c10ddcd3e169eea1c0d752a74093456c168e5d63a5eb496d15370bce8f501dae

test:
  secret_key_base: 83303d50f6f39795ad10f8db73f8094be305ff10316787865ddd176a3b107ca397226d59fd4c497a48da3962a337eca724afd22b1f04ce5c680eff1f9cd03458

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
